INSERT INTO products (ID,TITLE,PRICE,RAITING)
VALUES (1, 'banana', 6.99, 1);
INSERT INTO products (ID,TITLE,PRICE,RAITING)
VALUES (2, 'milkshake', 15.5, 2);
INSERT INTO products (ID,TITLE,PRICE,RAITING)
VALUES (3, 'burger', 39.99, 3);
INSERT INTO products (ID,TITLE,PRICE,RAITING)
VALUES (4, 'beer', 9.99, 4);
INSERT INTO products (ID,TITLE,PRICE,RAITING)
VALUES (5, 'strawberry', 24.99, 4);